// GENERATED by freecad-workspace export_cpp.py -- do not edit.
// SIM-derived design values (LQR from the linearized plant model). Not tuned or validated for the real robot.
#pragma once
#include <cstdint>
namespace balance_gains {
constexpr uint32_t kSchema = 1;
constexpr uint32_t kContractVersion = 1;
constexpr uint32_t kGainsHash = 0x1e60b0fcu;
constexpr float kLqrK[2] = { -23.8184299f, -3.49402261f };    // [theta, theta_dot]
constexpr float kThetaRefRad = -0.108599998f;
constexpr float kOutLimit = 1.0f;
constexpr float kPidKp = 1.0f, kPidKi = 0.100000001f, kPidKd = 0.0500000007f, kPidOutLimit = 1.0f;
}  // namespace balance_gains
