#!/usr/bin/env bash
# Convert an SVG to a 64x64 C array of uint32_t pixels in the format the
# wokwi-ttl-servo chip writes to its framebuffer: 0xAABBGGRR (R in the low
# byte). The pixel format is ASSUMED from Wokwi examples and is UNVERIFIED
# in the simulator; if colours look swapped, rerun with --bgr.
#
# Needs: inkscape (rasterizes SVG incl. <style> classes) and ImageMagick
# (magick or convert), plus od and awk.
#
# Usage:
#   svg_to_pixels.sh [--size N] [--hide-id ID]... [--flatten COLOR|none] [--bgr] [--name SYMBOL] in.svg [out.h]
#   --size N         output is N x N pixels (default 64; chip display is 64x64)
#   --hide-id ID     hide the SVG element with this id before rendering, e.g.
#                    `horn` to bake only the static servo body (the chip draws
#                    the rotating horn itself). Repeatable: each ID is hidden.
#   --flatten COLOR  after downscale, composite onto COLOR (default #202020) so
#                    every pixel is opaque (alpha 0xFF). `none` keeps transparency.
#   --bgr            swap R and B (use if red shows up blue in the GUI)
#   --name SYMBOL    C array name (default: servo_bg_pixels)
# Without out.h the array is printed to stdout.
set -euo pipefail

size=64
hide_ids=()
flatten="#202020"
swap=0
name="servo_bg_pixels"

while [ $# -gt 0 ]; do
  case "$1" in
    --size) size="$2"; shift 2 ;;
    --hide-id) hide_ids+=("$2"); shift 2 ;;
    --flatten) flatten="$2"; shift 2 ;;
    --bgr) swap=1; shift ;;
    --name) name="$2"; shift 2 ;;
    -h|--help) sed -n '2,/^set -euo/p' "$0" | sed '$d'; exit 0 ;;
    --) shift; break ;;
    -*) echo "unknown option: $1" >&2; exit 2 ;;
    *) break ;;
  esac
done

in="${1:-}"
out="${2:-}"
[ -n "$in" ] || { echo "usage: $0 [options] in.svg [out.h]" >&2; exit 2; }
[ -f "$in" ] || { echo "no such file: $in" >&2; exit 1; }
command -v inkscape >/dev/null || { echo "inkscape not found" >&2; exit 1; }
if command -v magick >/dev/null; then im=(magick); else im=(convert); fi
command -v "${im[0]}" >/dev/null || { echo "ImageMagick not found" >&2; exit 1; }

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# 1. Rasterize at 4x, then downscale with a box filter (cleaner edges than
#    rendering straight to 64 px). Transparent background stays transparent
#    unless --flatten is used (step 2).
big=$((size * 4))
actions=""
if [ "${#hide_ids[@]}" -gt 0 ]; then
  for id in "${hide_ids[@]}"; do
    actions="${actions}select-by-id:$id;object-set-attribute:style,display:none;select-clear;"
  done
fi
actions="${actions}export-type:png;export-filename:$tmp/big.png;export-width:$big;export-height:$big;export-background-opacity:0;export-do"
inkscape --actions="$actions" "$in" >/dev/null 2>&1
[ -f "$tmp/big.png" ] || { echo "inkscape produced no PNG" >&2; exit 1; }

# 2. Downscale to size x size; optionally flatten onto a solid colour so the
#    alpha channel is forced to 0xFF. Dump raw 8-bit RGBA bytes.
flat_on=0
if [ "$flatten" = "none" ]; then
  "${im[@]}" "$tmp/big.png" -filter Box -resize "${size}x${size}!" -depth 8 "rgba:$tmp/px.raw"
else
  flat_on=1
  "${im[@]}" "$tmp/big.png" -filter Box -resize "${size}x${size}!" \
    -background "$flatten" -alpha remove -alpha off \
    -alpha on -channel A -evaluate set 100% +channel \
    -depth 8 "rgba:$tmp/px.raw"
fi
bytes=$(wc -c < "$tmp/px.raw")
[ "$bytes" -eq $((size * size * 4)) ] || { echo "unexpected raw size: $bytes" >&2; exit 1; }

# 3. Format as 0xAABBGGRR (little-endian uint32 of bytes R,G,B,A).
#    With flattening, every alpha byte must be 255 or the script fails.
emit() {
  echo "// GENERATED FILE - DO NOT EDIT. Regenerate with: make wokwi_ttl_servo-bg"
  echo "// Generated by programs/wokwi_ttl_servo/tools/svg_to_pixels.sh from $(basename "$in")"
  echo "// ${size}x${size}, 0xAABBGGRR$([ "$swap" -eq 1 ] && echo ' (R/B swapped)'). Pixel format UNVERIFIED in the simulator."
  echo "#include <stdint.h>"
  echo
  echo "static const uint32_t ${name}[${size} * ${size}] = {"
  od -An -v -tu1 -w4 "$tmp/px.raw" | awk -v swap="$swap" -v chk="$flat_on" '
    { r=$1; g=$2; b=$3; a=$4
      if (chk && a != 255) bad=1
      if (swap) { t=r; r=b; b=t }
      printf "0x%02X%02X%02X%02X,", a, b, g, r
      if (NR % 8 == 0) printf "\n"; else printf " " }
    END {
      if (bad) { print "error: non-opaque pixel after --flatten" > "/dev/stderr"; exit 1 }
      if (NR % 8 != 0) printf "\n" }'
  echo "};"
}

if [ -n "$out" ]; then emit > "$out"; echo "wrote $out" >&2; else emit; fi
